set(_CATKIN_CURRENT_PACKAGE "webcam_publisher")
set(webcam_publisher_VERSION "0.0.0")
set(webcam_publisher_MAINTAINER "user <user@todo.todo>")
set(webcam_publisher_PACKAGE_FORMAT "2")
set(webcam_publisher_BUILD_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(webcam_publisher_BUILD_EXPORT_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(webcam_publisher_BUILDTOOL_DEPENDS "catkin")
set(webcam_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(webcam_publisher_EXEC_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(webcam_publisher_RUN_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(webcam_publisher_TEST_DEPENDS )
set(webcam_publisher_DOC_DEPENDS )
set(webcam_publisher_URL_WEBSITE "")
set(webcam_publisher_URL_BUGTRACKER "")
set(webcam_publisher_URL_REPOSITORY "")
set(webcam_publisher_DEPRECATED "")