set(_CATKIN_CURRENT_PACKAGE "body_urdf_files")
set(body_urdf_files_VERSION "1.0.0")
set(body_urdf_files_MAINTAINER " <elzeft@email.com>")
set(body_urdf_files_PACKAGE_FORMAT "2")
set(body_urdf_files_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "geometry_msgs" "urdf" "xacro" "std_msgs" "message_generation" "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "joint_state_publisher_gui" "gazebo" "moveit_simple_controller_manager")
set(body_urdf_files_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "urdf" "xacro" "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "joint_state_publisher_gui" "gazebo" "moveit_simple_controller_manager")
set(body_urdf_files_BUILDTOOL_DEPENDS "catkin")
set(body_urdf_files_BUILDTOOL_EXPORT_DEPENDS )
set(body_urdf_files_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "urdf" "xacro" "message_runtime" "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "joint_state_publisher_gui" "gazebo" "moveit_simple_controller_manager")
set(body_urdf_files_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "urdf" "xacro" "message_runtime" "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "joint_state_publisher_gui" "gazebo" "moveit_simple_controller_manager")
set(body_urdf_files_TEST_DEPENDS )
set(body_urdf_files_DOC_DEPENDS )
set(body_urdf_files_URL_WEBSITE "")
set(body_urdf_files_URL_BUGTRACKER "")
set(body_urdf_files_URL_REPOSITORY "")
set(body_urdf_files_DEPRECATED "")