set(_CATKIN_CURRENT_PACKAGE "movit_humanoid")
set(movit_humanoid_VERSION "0.3.0")
set(movit_humanoid_MAINTAINER "Perry <perry@email.com>")
set(movit_humanoid_PACKAGE_FORMAT "1")
set(movit_humanoid_BUILD_DEPENDS )
set(movit_humanoid_BUILD_EXPORT_DEPENDS "gazebo_ros_control" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "joint_trajectory_controller" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "body_urdf_files")
set(movit_humanoid_BUILDTOOL_DEPENDS "catkin")
set(movit_humanoid_BUILDTOOL_EXPORT_DEPENDS )
set(movit_humanoid_EXEC_DEPENDS "gazebo_ros_control" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "joint_trajectory_controller" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "body_urdf_files")
set(movit_humanoid_RUN_DEPENDS "gazebo_ros_control" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "joint_trajectory_controller" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "body_urdf_files")
set(movit_humanoid_TEST_DEPENDS )
set(movit_humanoid_DOC_DEPENDS )
set(movit_humanoid_URL_WEBSITE "http://moveit.ros.org/")
set(movit_humanoid_URL_BUGTRACKER "https://github.com/moveit/moveit/issues")
set(movit_humanoid_URL_REPOSITORY "https://github.com/moveit/moveit")
set(movit_humanoid_DEPRECATED "")