set(_CATKIN_CURRENT_PACKAGE "orb_slam3_ros")
set(orb_slam3_ros_VERSION "0.0.0")
set(orb_slam3_ros_MAINTAINER "user <user@todo.todo>")
set(orb_slam3_ros_PACKAGE_FORMAT "2")
set(orb_slam3_ros_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(orb_slam3_ros_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(orb_slam3_ros_BUILDTOOL_DEPENDS "catkin")
set(orb_slam3_ros_BUILDTOOL_EXPORT_DEPENDS )
set(orb_slam3_ros_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(orb_slam3_ros_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(orb_slam3_ros_TEST_DEPENDS )
set(orb_slam3_ros_DOC_DEPENDS )
set(orb_slam3_ros_URL_WEBSITE "")
set(orb_slam3_ros_URL_BUGTRACKER "")
set(orb_slam3_ros_URL_REPOSITORY "")
set(orb_slam3_ros_DEPRECATED "")